---
api_contact_form:
    methods: [POST]
    # Configure path behind Firewall prefix…
    path: /api/1.0/forms/contact
    defaults:
        _controller: App\Controller\ContactFormController::formAction
        _locale: en
        _format: json
