---
appNamespace: '%env(string:APP_NAMESPACE)%'
timezone: '%env(string:APP_TIMEZONE)%'
staticDomainName: '%env(string:APP_STATIC_DOMAIN_NAME)%'
doctrine:
    driver: "pdo_mysql"
    host: '%env(string:MYSQL_HOST)%'
    user: '%env(string:MYSQL_USER)%'
    password: '%env(string:MYSQL_PASSWORD)%'
    dbname: '%env(string:MYSQL_DATABASE)%'
    server_version: '%env(string:MYSQL_VERSION)%'
    # "utf8mb4" charset requires at least mysql 5.7
    # due to large index requirement.
    # otherwise change it to "utf8"
    charset: utf8mb4
    default_table_options:
        charset: utf8mb4
        collate: utf8mb4_unicode_ci
# Choose a Doctrine strategy for NodesSources
# inheritance classes. BE CAREFUL, if you change this
# setting after creating content in your website, all
# node-sources data will be lost.
inheritance:
    type: single_table
# http://symfony.com/doc/current/reference/configuration/doctrine.html#caching-drivers
# If null or empty, Roadiz will use ArrayCache
cacheDriver:
    type: apcu
    host: ~
    port: ~
security:
    secret: '%env(string:APP_SECURITY_SECRET)%'
    session_name: '%env(string:APP_SECURITY_SESSION_NAME)%'
    session_cookie_secure: '%env(bool:APP_SECURITY_COOKIE_SECURE)%'
    session_cookie_httponly: true
    algorithm: argon2i

mailer:
    type: '%env(string:MAILER_TYPE)%'
    host: '%env(string:MAILER_HOST)%'
    port: '%env(int:MAILER_PORT)%'
    encryption: '%env(MAILER_ENCRYPTION)%'
    username: '%env(MAILER_USER)%'
    password: '%env(MAILER_PASSWORD)%'

# Lifetime of remember-me cookie in seconds (30 days)
rememberMeLifetime: 2592000
# Image intervention and Intervention Request
# settings for generating image on the fly
assetsProcessing:
    # gd or imagick (gd does not support TIFF and PSD formats)
    driver: '%env(string:APP_ASSETS_DRIVER)%'
    defaultQuality: '%env(int:APP_ASSETS_DEFAULT_QUALITY)%'
    # pixel size limit () after roadiz
    # should create a smaller copy.
    maxPixelSize: '%env(int:APP_ASSETS_MAX_PIXEL_SIZE)%'
    jpegoptimPath: /usr/bin/jpegoptim
    pngquantPath: /usr/bin/pngquant
    subscribers: []

#
# Messenger non-default configuration
#
messenger:
    failure_transport: 'failed_default'
    transports:
        default:
            dsn: '%env(string:APP_MESSENGER_DEFAULT_TRANSPORT_DSN)%'
            options: []
        async:
            dsn: 'doctrine://default?queue_name=async'
            options: []
        failed_default:
            dsn: 'doctrine://default?queue_name=failed_default'
            options: []
    routing:
        RZ\Roadiz\Message\AsyncMessage: async

#
# Reverse proxy invalidation
#
reverseProxyCache:
    frontend:
        varnish:
            host: '%env(string:VARNISH_HOST)%'
            domainName: '%env(string:VARNISH_DOMAIN)%'

#
# Monolog configuration
#
monolog:
    handlers:
        default:
            type: rotating_file
            path: '%kernel.log_dir%/roadiz.log'
            level: INFO
#        sentry:
#            type: sentry
#            level: WARNING
#            url: '%env(string:APP_SENTRY_DSN)%'

#
# Solr endpoint example
#
#solr:
#    endpoint:
#        localhost:
#            host: '%env(string:SOLR_HOST)%'
#            port: '%env(int:SOLR_PORT)%'
#            path: "/"
#            core: '%env(string:SOLR_CORE_NAME)%'
#            timeout: 3
#            username: ""
#            password: ""

